
name: CI
on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '8.6.5'
          projectPath: '${{ github.workspace }}/API'
          args: '-runMode=console -projectPath="C:\Users\Tanushree SG\git\API\Pi API testing.prj" -testSuitePath="Test Suites/chain" -browserType="Web Service" -executionProfile="default" -apiKey="2742c98b-ca6f-4054-b0c5-6c74cc19932b" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'
    - name: Execute Katalon Script
      run: |
        katalonc -noSplash -runMode=console -projectPath="C:\Users\Tanushree SG\git\API\Pi API testing.prj" -retry=0 -testSuitePath="Test Suites/chain" -browserType="Web Service" -executionProfile="default" -apiKey="2742c98b-ca6f-4054-b0c5-6c74cc19932b" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true


