name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Katalon Studio Github Action
        uses: katalon-studio/katalon-studio-github-action@v2
        with:
          version: '8.6.6'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -statusDelay=15 -testSuiteCollections="Test Suites\chain" -apiKey="${{secrets.KATALON_API_KEY}} --config -webui.autoUpdateDrivers=true'

      # Add your build steps here

      - name: Trigger Second Workflow
        uses: repo-dispatch/action@v1
        with:
          token: ${{ secrets.TOKEN }}
          owner: TanushreeSG
          repo: demo_api
          event_type: start-second-workflow
          client_payload: |
            key: value
