name: Katalon Studio CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '8.6.5'
          projectPath: 'C:\Users\Tanushree SG\Desktop\Pi API testing'
          args: '-runMode=console -projectPath="C:\Users\Tanushree SG\Desktop\Pi API testing\Pi API testing.prj" -testSuitePath="Test Suites/chain" -browserType="Web Service" -executionProfile="default" -apiKey="${{secrets.KATALON_API_KEY}}" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true'
    - name: Execute Katalon Script
      run: |
        katalonc -noSplash -runMode=console -projectPath="C:\Users\Tanushree SG\Desktop\Pi API testing\Pi API testing.prj" -retry=0 -testSuitePath="Test Suites/chain" -browserType="Web Service" -executionProfile="default" -apiKey="${{ secrets.KATALON_API_KEY }}" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true


