
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '8.6.6'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -statusDelay=15 -testSuiteCollections="Test Suites\chain" -apiKey="${{secrets.KATALON_API_KEY}} --config -webui.autoUpdateDrivers=true'

    - name: Trigger Workflow in Another Repository
      run: |
        curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer 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" \
          "https://api.github.com/repos/TanushreeSG/demo-web/dispatches"
      if: success()












