name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
<<<<<<< HEAD
    - uses: actions/checkout@v2
=======
      uses: actions/checkout@v2
>>>>>>> 55a390c80608663f083f41ee54f3aa0edf84a939
    - name: Katalon Studio Github Action
      uses: katalon-studio/katalon-studio-github-action@v2
      with:
          version: '8.6.5'
          projectPath: '${{ github.workspace }}'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Sample Test Suite" -browserType="TestCloud" -testcloudEnvironmentId="256" -apiKey= ${{ secrets.API_KEY }} --config -webui.autoUpdateDrivers=true'
